name: "Tests"
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v8
      - name: Build all interpreters and tarballs
        run: nix-build -A interpreters -A tarballs