name: "Tests"
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v8
      - name: Build and push to cachix
        uses: cachix/cachix-action@v5
        with:
          name: static-python
          attributes: tarballs
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'